"""Add foreign key constraints to tenant references

Revision ID: 618fd9555930
Revises: 001
Create Date: 2025-08-16 11:28:43.620938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '618fd9555930'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'dlq', 'tenants', ['tenant'], ['name'])
    op.create_foreign_key(None, 'exceptions', 'tenants', ['tenant'], ['name'])
    op.drop_index('ix_adjustments_tenant', table_name='invoice_adjustments')
    op.create_index(op.f('ix_invoice_adjustments_tenant'), 'invoice_adjustments', ['tenant'], unique=False)
    op.create_foreign_key(None, 'invoice_adjustments', 'tenants', ['tenant'], ['name'])
    op.create_foreign_key(None, 'invoices', 'tenants', ['tenant'], ['name'])
    op.create_foreign_key(None, 'order_events', 'tenants', ['tenant'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_events', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoice_adjustments', type_='foreignkey')
    op.drop_index(op.f('ix_invoice_adjustments_tenant'), table_name='invoice_adjustments')
    op.create_index('ix_adjustments_tenant', 'invoice_adjustments', ['tenant'], unique=False)
    op.drop_constraint(None, 'exceptions', type_='foreignkey')
    op.drop_constraint(None, 'dlq', type_='foreignkey')
    # ### end Alembic commands ###
